/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IConscription, IConscriptionInterface } from "../IConscription";

const _abi = [
  {
    inputs: [],
    name: "lockupAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "profiles",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IConscription__factory {
  static readonly abi = _abi;
  static createInterface(): IConscriptionInterface {
    return new utils.Interface(_abi) as IConscriptionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConscription {
    return new Contract(address, _abi, signerOrProvider) as IConscription;
  }
}
