/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IsROME, IsROMEInterface } from "../IsROME";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gons",
        type: "uint256",
      },
    ],
    name: "balanceForGons",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IsROME__factory {
  static readonly abi = _abi;
  static createInterface(): IsROMEInterface {
    return new utils.Interface(_abi) as IsROMEInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IsROME {
    return new Contract(address, _abi, signerOrProvider) as IsROME;
  }
}
