/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IConscriptionInterface extends utils.Interface {
  contractName: "IConscription";
  functions: {
    "lockupAmount()": FunctionFragment;
    "profiles(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "lockupAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "profiles", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "lockupAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;

  events: {};
}

export interface IConscription extends BaseContract {
  contractName: "IConscription";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IConscriptionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    lockupAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    profiles(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber]>;
  };

  lockupAmount(overrides?: CallOverrides): Promise<BigNumber>;

  profiles(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, BigNumber]>;

  callStatic: {
    lockupAmount(overrides?: CallOverrides): Promise<BigNumber>;

    profiles(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    lockupAmount(overrides?: CallOverrides): Promise<BigNumber>;

    profiles(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    lockupAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    profiles(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
