/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RomeAuthorityInterface extends utils.Interface {
  contractName: "RomeAuthority";
  functions: {
    "authority()": FunctionFragment;
    "governor()": FunctionFragment;
    "guardian()": FunctionFragment;
    "newGovernor()": FunctionFragment;
    "newGuardian()": FunctionFragment;
    "newPolicy()": FunctionFragment;
    "newVault()": FunctionFragment;
    "policy()": FunctionFragment;
    "pullGovernor()": FunctionFragment;
    "pullGuardian()": FunctionFragment;
    "pullPolicy()": FunctionFragment;
    "pullVault()": FunctionFragment;
    "pushGovernor(address,bool)": FunctionFragment;
    "pushGuardian(address,bool)": FunctionFragment;
    "pushPolicy(address,bool)": FunctionFragment;
    "pushVault(address,bool)": FunctionFragment;
    "setAuthority(address)": FunctionFragment;
    "vault()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(functionFragment: "guardian", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newGovernor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "newPolicy", values?: undefined): string;
  encodeFunctionData(functionFragment: "newVault", values?: undefined): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pullGovernor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pullGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pullPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pullVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pushGovernor",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "pushGuardian",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "pushPolicy",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "pushVault",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pullGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pullGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pullPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pullVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pushGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pushPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pushVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;

  events: {
    "AuthorityUpdated(address)": EventFragment;
    "GovernorPulled(address,address)": EventFragment;
    "GovernorPushed(address,address,bool)": EventFragment;
    "GuardianPulled(address,address)": EventFragment;
    "GuardianPushed(address,address,bool)": EventFragment;
    "PolicyPulled(address,address)": EventFragment;
    "PolicyPushed(address,address,bool)": EventFragment;
    "VaultPulled(address,address)": EventFragment;
    "VaultPushed(address,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernorPulled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernorPushed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GuardianPulled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GuardianPushed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PolicyPulled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PolicyPushed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultPulled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultPushed"): EventFragment;
}

export type AuthorityUpdatedEvent = TypedEvent<[string], { authority: string }>;

export type AuthorityUpdatedEventFilter =
  TypedEventFilter<AuthorityUpdatedEvent>;

export type GovernorPulledEvent = TypedEvent<
  [string, string],
  { from: string; to: string }
>;

export type GovernorPulledEventFilter = TypedEventFilter<GovernorPulledEvent>;

export type GovernorPushedEvent = TypedEvent<
  [string, string, boolean],
  { from: string; to: string; _effectiveImmediately: boolean }
>;

export type GovernorPushedEventFilter = TypedEventFilter<GovernorPushedEvent>;

export type GuardianPulledEvent = TypedEvent<
  [string, string],
  { from: string; to: string }
>;

export type GuardianPulledEventFilter = TypedEventFilter<GuardianPulledEvent>;

export type GuardianPushedEvent = TypedEvent<
  [string, string, boolean],
  { from: string; to: string; _effectiveImmediately: boolean }
>;

export type GuardianPushedEventFilter = TypedEventFilter<GuardianPushedEvent>;

export type PolicyPulledEvent = TypedEvent<
  [string, string],
  { from: string; to: string }
>;

export type PolicyPulledEventFilter = TypedEventFilter<PolicyPulledEvent>;

export type PolicyPushedEvent = TypedEvent<
  [string, string, boolean],
  { from: string; to: string; _effectiveImmediately: boolean }
>;

export type PolicyPushedEventFilter = TypedEventFilter<PolicyPushedEvent>;

export type VaultPulledEvent = TypedEvent<
  [string, string],
  { from: string; to: string }
>;

export type VaultPulledEventFilter = TypedEventFilter<VaultPulledEvent>;

export type VaultPushedEvent = TypedEvent<
  [string, string, boolean],
  { from: string; to: string; _effectiveImmediately: boolean }
>;

export type VaultPushedEventFilter = TypedEventFilter<VaultPushedEvent>;

export interface RomeAuthority extends BaseContract {
  contractName: "RomeAuthority";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RomeAuthorityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authority(overrides?: CallOverrides): Promise<[string]>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    guardian(overrides?: CallOverrides): Promise<[string]>;

    newGovernor(overrides?: CallOverrides): Promise<[string]>;

    newGuardian(overrides?: CallOverrides): Promise<[string]>;

    newPolicy(overrides?: CallOverrides): Promise<[string]>;

    newVault(overrides?: CallOverrides): Promise<[string]>;

    policy(overrides?: CallOverrides): Promise<[string]>;

    pullGovernor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pullGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pullPolicy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pullVault(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushGovernor(
      _newGovernor: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushGuardian(
      _newGuardian: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushPolicy(
      _newPolicy: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushVault(
      _newVault: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vault(overrides?: CallOverrides): Promise<[string]>;
  };

  authority(overrides?: CallOverrides): Promise<string>;

  governor(overrides?: CallOverrides): Promise<string>;

  guardian(overrides?: CallOverrides): Promise<string>;

  newGovernor(overrides?: CallOverrides): Promise<string>;

  newGuardian(overrides?: CallOverrides): Promise<string>;

  newPolicy(overrides?: CallOverrides): Promise<string>;

  newVault(overrides?: CallOverrides): Promise<string>;

  policy(overrides?: CallOverrides): Promise<string>;

  pullGovernor(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pullGuardian(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pullPolicy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pullVault(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushGovernor(
    _newGovernor: string,
    _effectiveImmediately: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushGuardian(
    _newGuardian: string,
    _effectiveImmediately: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushPolicy(
    _newPolicy: string,
    _effectiveImmediately: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushVault(
    _newVault: string,
    _effectiveImmediately: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuthority(
    _newAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    authority(overrides?: CallOverrides): Promise<string>;

    governor(overrides?: CallOverrides): Promise<string>;

    guardian(overrides?: CallOverrides): Promise<string>;

    newGovernor(overrides?: CallOverrides): Promise<string>;

    newGuardian(overrides?: CallOverrides): Promise<string>;

    newPolicy(overrides?: CallOverrides): Promise<string>;

    newVault(overrides?: CallOverrides): Promise<string>;

    policy(overrides?: CallOverrides): Promise<string>;

    pullGovernor(overrides?: CallOverrides): Promise<void>;

    pullGuardian(overrides?: CallOverrides): Promise<void>;

    pullPolicy(overrides?: CallOverrides): Promise<void>;

    pullVault(overrides?: CallOverrides): Promise<void>;

    pushGovernor(
      _newGovernor: string,
      _effectiveImmediately: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    pushGuardian(
      _newGuardian: string,
      _effectiveImmediately: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    pushPolicy(
      _newPolicy: string,
      _effectiveImmediately: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    pushVault(
      _newVault: string,
      _effectiveImmediately: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthority(
      _newAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;

    vault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AuthorityUpdated(address)"(
      authority?: string | null
    ): AuthorityUpdatedEventFilter;
    AuthorityUpdated(authority?: string | null): AuthorityUpdatedEventFilter;

    "GovernorPulled(address,address)"(
      from?: string | null,
      to?: string | null
    ): GovernorPulledEventFilter;
    GovernorPulled(
      from?: string | null,
      to?: string | null
    ): GovernorPulledEventFilter;

    "GovernorPushed(address,address,bool)"(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): GovernorPushedEventFilter;
    GovernorPushed(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): GovernorPushedEventFilter;

    "GuardianPulled(address,address)"(
      from?: string | null,
      to?: string | null
    ): GuardianPulledEventFilter;
    GuardianPulled(
      from?: string | null,
      to?: string | null
    ): GuardianPulledEventFilter;

    "GuardianPushed(address,address,bool)"(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): GuardianPushedEventFilter;
    GuardianPushed(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): GuardianPushedEventFilter;

    "PolicyPulled(address,address)"(
      from?: string | null,
      to?: string | null
    ): PolicyPulledEventFilter;
    PolicyPulled(
      from?: string | null,
      to?: string | null
    ): PolicyPulledEventFilter;

    "PolicyPushed(address,address,bool)"(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): PolicyPushedEventFilter;
    PolicyPushed(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): PolicyPushedEventFilter;

    "VaultPulled(address,address)"(
      from?: string | null,
      to?: string | null
    ): VaultPulledEventFilter;
    VaultPulled(
      from?: string | null,
      to?: string | null
    ): VaultPulledEventFilter;

    "VaultPushed(address,address,bool)"(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): VaultPushedEventFilter;
    VaultPushed(
      from?: string | null,
      to?: string | null,
      _effectiveImmediately?: null
    ): VaultPushedEventFilter;
  };

  estimateGas: {
    authority(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    guardian(overrides?: CallOverrides): Promise<BigNumber>;

    newGovernor(overrides?: CallOverrides): Promise<BigNumber>;

    newGuardian(overrides?: CallOverrides): Promise<BigNumber>;

    newPolicy(overrides?: CallOverrides): Promise<BigNumber>;

    newVault(overrides?: CallOverrides): Promise<BigNumber>;

    policy(overrides?: CallOverrides): Promise<BigNumber>;

    pullGovernor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pullGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pullPolicy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pullVault(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushGovernor(
      _newGovernor: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushGuardian(
      _newGuardian: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushPolicy(
      _newPolicy: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushVault(
      _newVault: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    authority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    guardian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newGovernor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newGuardian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newPolicy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    policy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pullGovernor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pullGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pullPolicy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pullVault(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushGovernor(
      _newGovernor: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushGuardian(
      _newGuardian: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushPolicy(
      _newPolicy: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushVault(
      _newVault: string,
      _effectiveImmediately: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
